- hosts: all
  become: yes
  become_method: sudo
  remote_user: ubuntu

  vars:
    dir: /home/ubuntu/
    app_dir: /home/ubuntu/Piggymetrics
    ansible_python_interpreter: '/usr/bin/python3'

  roles:
    - setup
    - webserver
    - jenkins
    - aws
    - k8s
    - docker

  environment:
    AWS_SECRET_ACCESS_KEY: "{{ lookup('env', 'AWS_SECRET_ACCESS_KEY') }}"
    AWS_ACCESS_KEY_ID: "{{ lookup('env', 'AWS_ACCESS_KEY_ID') }}"
    AWS_REGION: us-east-1
