---
- name: install necessary packages
  apt:
    update_cache: yes
    name: "{{ item }}"
    state: present
  with_items:
    - awscli
    - default-jre
    - default-jdk
    - nginx
    - python-pip
